/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmr.application;

import jmr.iu.Cartesian3DPanel;
import jmr.result.ResultList;

/**
 *
 * @author alejandro
 */
public class Cartesian3DInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cartesian2DJInternalFrame
     */
    
    Cartesian3DPanel carsetian3dpanel;
    
    public Cartesian3DInternalFrame() {
        initComponents();
        
        carsetian3dpanel = new Cartesian3DPanel();
        
        getContentPane().add(carsetian3dpanel,java.awt.BorderLayout.CENTER);
        
    }
    
    public Cartesian3DInternalFrame(ResultList list){
        this();
        if(list!= null){
            carsetian3dpanel.add(list);
            System.setProperty("sun.awt.noerasebackground", "true");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cartesian 3D visualization");
        setPreferredSize(new java.awt.Dimension(500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
