/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmr.application;

import jmr.iu.Polar3DPanel;
import jmr.iu.RingPanel3D;
import jmr.result.ResultList;

/**
 *
 * @author alejandro
 */
public class Polar3DInternalFrame extends javax.swing.JInternalFrame {

    
    RingPanel3D polar3dpanel;
    
    public Polar3DInternalFrame() {
        initComponents();
        
        polar3dpanel = new RingPanel3D();
        
        getContentPane().add(polar3dpanel,java.awt.BorderLayout.CENTER);
        
    }
    
    public Polar3DInternalFrame(ResultList list){
        this();
        if(list!= null){
            polar3dpanel.add(list);
            System.setProperty("sun.awt.noerasebackground", "true");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Polar 3D visualization");
        setPreferredSize(new java.awt.Dimension(500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
