/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmr.application;

import jmr.iu.SpiralPanel;
import jmr.result.ResultList;

/**
 *
 * @author alejandro
 */

public class SpiralInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SpiralInternalFrame
     */
    
    private SpiralPanel spiralpanel;
    
    
    public SpiralInternalFrame() {
        initComponents();
        
        spiralpanel = new SpiralPanel();
        
        getContentPane().add(spiralpanel, java.awt.BorderLayout.CENTER);
    }
    
    public SpiralInternalFrame(ResultList list){
        this();
        if(list != null){
            spiralpanel.add(list);
            System.setProperty("sun.awt.noerasebackground", "true");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Spiral visualization");
        setPreferredSize(new java.awt.Dimension(500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
